### ISSUE TITLE
Errore C.SI.5.1 - CERTIFICATO HTTPS

### ISSUE THREAD

**Issue by MarcoTesta-EP** [italia/pa-website-validator-gui#4]
Buonasera,
abbiamo fatto girare il nuovo tool su alcuni nostri siti ed otteniamo un errore di certificato ad esempio su questo comune:

![image](https://github.com/user-attachments/assets/3c1e7fd1-0032-40fb-a9ec-28b1c91dad0c)

La suite di cifratura utilizzata (se non erro) è tra quelle indicate nella documentazione AGID riportata qui: https://cert-agid.gov.it/wp-content/uploads/2020/11/AgID-RACCSECTLS-01.pdf

Segnalo anche un problema nelle date riportate di validità del certificato che è valido dal 16/12/2023 (e non 16/11 come indicato) al 16/01/2025.

Dove sta l'errore? 
Grazie!

Marco Testa

**Comment by MarcoTesta-EP** [comment]
Un aggiornamento su questo: abbiamo richiesto sullo stesso comune la verifica del protocollo HTTPS sul sito di AGID https://cert-agid.gov.it/verifica-https-cms/ ed il risultato è positivo:

![image](https://github.com/user-attachments/assets/7e1d8833-b506-40c4-b595-ba4cdd85c0b0)

Il mio dubbio è sulla durata dell'SSL, nel nostro caso sono 13 mesi che comunque è un valore ammesso a livello internazionale (durata max 397 giorni).

Vi pregherei se possibile di dare priorità alla cosa, abbiamo un paio di comuni che hanno ottenuto un risultato parziale di asseverazione per questo motivo.
Grazie!

Marco Testa

**Comment by alander73** [comment]
Ciao Marco, io non sono uno specialista quindi non vorrei dire castronerie di sorta;confermo che anche a me da l'errore sulla crittografia (ho verificato alcuni siti di utenti che usano il nostro CMS);se non erro c'è una revisione del documento 
(https://www.agid.gov.it/sites/agid/files/2024-07/Allegato%202%20-%20Raccomandazioni%20in%20merito%20allo%20standard%20Transport%20Layer%20Security%20%28TLS%29.pdf)
mi pare di capire che ci siano delle suite di cifratura obbligatorie e/o ben definite per TLS 1.3? ?!

![Errore Crawler](https://github.com/user-attachments/assets/5a67409f-6c50-419a-8dfd-8986c8f3c79f)

![Cihper](https://github.com/user-attachments/assets/67d851f6-8ab8-4ac7-a93f-902fbe16ae63)

Oltre a questo il crawler segna la data di validità con uno scarto di un mese,mi pare.
Non so se le info inserite possano essere utili...ne so veramente poco, nel merito.
Saluti
Alan

**Comment by MarcoTesta-EP** [comment]
Ciao Alan,
grazie della versione aggiornata del documento, lo verifico.
Nel mio caso sto utilizzando TLS 1.2 con le suite di cifratura indicate, purtroppo l'errore non aiuta nella soluzione.
Continuo ad indagare aggiorno la issue in caso di novità.
Grazie.

Marco

**Comment by si78-smurf** [comment]
Ciao,
Javascript conta i mesi partendo da 0, potrebbe essere questo il problema?
Un saluto

**Comment by alander73** [comment]
Ciao [si78-smurf] penso possa essere,non saprei; queste le misure della validità del certificato con Crawler e viste con un browser (chrome)
<img width="413" alt="browser_certificate" src="https://github.com/user-attachments/assets/5672c1e6-0ba1-4c23-975e-9c9833ace7dc">
<img width="135" alt="Crawler_Date" src="https://github.com/user-attachments/assets/05b9da84-2d18-493b-a5b2-5290ee43092e">

**Comment by MarcoTesta-EP** [comment]
Ho fatto un pò mente locale anche grazie all'aiuto del Team NordOvest del Dipartimento, le cose anomale che ho riscontrato nel report del comune di Granozzo con Monticello riportato nel primo post sono:

1. La versione del TLS indicata dal report è 1.3, in realtà quella utilizzata è la 1.2
2. La suite di cifratura indicata (che potrebbe essere quella effettivamente usata) è valida per la versione TLS 1.2 ma non per la 1.3, quindi la suite potrebbe essere identificata come errata perchè la versione TLS rilevata è errata
3. Le date di validità del certificato non tornano con quelle reali del certificato

Ricordo anche che il report AGID sullo stesso comune riporta un risultato positivo, quindi c'è discrepanza tra i due.

Chiedo quindi agli sviluppatori se è possibile verificare i vari punti indicati, la cosa come detto è sensibile se gli asseveratori inizieranno a rimandare i comuni sulla base del risultato negativo.
Grazie.

**Comment by alander73** [comment]
Ciao Marco, 
ribadendo la mia limitata "esperienza nel merito" forse ho capito dove potrebbe risiedere l'errore.
concordo appieno; Penso che l'applicativo "recuperi un informazione errata" in merito alla versione TLS; potrebbe  essere un errore di codice?! màh?
Mi pare di capire che:
- Confonda il metodo di criptaggio della connessione (tunnel) e dell'autentica che è TLS 1.2
<img width="377" alt="Versione di autenticazione-encryping TLS del Sito" src="https://github.com/user-attachments/assets/cbcf2e18-a29c-4771-ba2f-65460ebfdfdf">

con
- la versione del Certificato -> che è 3
<img width="430" alt="Vrersione del certificato" src="https://github.com/user-attachments/assets/1b472f72-6c39-4cc1-8b73-56bf4f1e5137">

Le immagini allegate provengono da un sito che lamenta l'errore visto dal crwaler, analizzate con Browser Chrome funzione
-> Developer Tool -> Security
Naturalmente è un idea...se fosse davvero cosi' si spiegherebbe l'incongruenza e l'errore come da tuoi punti 2/ e 2.1.3
perchè,come dici anche tu, si trova una suite errata rispetto al TLS rilevato.

Spero siano note interessanti e "usabili" per un eventuale debugging.
Saluti
Alan

**Comment by MarcoTesta-EP** [comment]
Ci sono novità su questo problema? Grazie!

**Comment by lorenzo-vernocchi** [comment]
Buongiorno @MarcoTesta-EP, grazie per la segnalazione
il problema dovrebbe essere risolto con la versione v1.0.28.

La versione TLS rilevata in ambiente Electron differisce da quella rilevato in ambiente Node. Electron (GUI) utilizza BoringSSL e non OpenSSL. La logica di rilevamento della versione TLS è stata riscritta usando una libreria che garantisce un comportamento coerente.
