### ISSUE TITLE
App danneggiata arm MacOS

### ISSUE THREAD

**Issue by vincenzolegrottaglie** [italia/pa-website-validator-gui#5]
Qualsiasi delle due release per Mac con processori arm restituisce questo errore. Anche provando a scaricare più volte il file. Non si tratta di download andato male.
Allego screenshot:
<img width="290" alt="Screenshot 2024-12-05 alle 09 57 05" src="https://github.com/user-attachments/assets/ff770b2b-ad2a-4279-b78a-ce9be9a4a5dd">

**Comment by NicolaZivago** [comment]
Confermo, anche io con Mac ARM ho lo stesso errore

**Comment by vincenzolegrottaglie** [comment]
L'avevo letto ma non lo avevo provato sinceramente. Parlava di app di sviluppatore sconosciuto, non di danneggiata. Comunque funziona. Grazie
